### ISSUE TITLE
OpenAPI date-time mappings

### ISSUE THREAD

**Issue by ovrays** [kora-projects/kora#130]
**Versions:**
- Kora - 1.1.9
- Kotlin - 2.0.20
- OpenAPI Generator - 7.4.0

**Описание проблемы / Describe the bug:**

The use of mapping to have the `DateTime` type in OpenAPI represented as `java.time.Instant` is ignored
The generated type still remains `java.time.OffsetDateTime`

```kt
openApiGenerate {
    generatorName = "kora"
    
    ..
    
    configOptions = mapOf(
        "mode" to "kotlin-server",
        "dateLibrary" to "java8",
        "typeMappings" to "DateTime=Instant",
        "importMappings" to "Instant=java.time.Instant"
    )
}
```

**Текущее поведение / Current behavior:**

The use of mappings is ignored

**Ожидаемое поведение / Expected behavior:**

The use of mappings isn't ignored

**Стек вызова или сгенерированный код или скриншоты / Stacktrace or generated code or screenshots (*Optional*):**

```kt
data class StorageFile @ru.tinkoff.kora.json.common.annotation.JsonReader constructor (
  @ru.tinkoff.kora.json.common.annotation.JsonField("name")
  val name: String,
  @ru.tinkoff.kora.json.common.annotation.JsonField("createdAt")
  val createdAt: java.time.OffsetDateTime,
  @ru.tinkoff.kora.json.common.annotation.JsonField("updatedAt")
  val updatedAt: java.time.OffsetDateTime,
  @ru.tinkoff.kora.json.common.annotation.JsonField("isDirectory")
  val isDirectory: Boolean
)
```

**Comment by GoodforGod** [comment]
Correct usage:

```groovy
openApiGenerate{
    typeMappings = [ "DateTime" : "java.time.Instant" ]
}
```
